---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/projects/kingscorner/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - /bin/mkdir -p ${DEPLOYPATH}tmp
    - touch ${DEPLOYPATH}tmp/restart.txt
